### ISSUE TITLE
How can I access the old version of tidyLPA?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/tidyLPA#101]
How can I access the old version of tidyLPA (v. `0.2.4`)?

**Comment by jrosen48** [comment]
The last version of tidyLPA [before the major, breaking changes](https://data-edu.github.io/tidyLPA/articles/introduction-to-major-changes.html] (which was version `0.2.4`) can no longer be downloaded from CRAN but can be downloaded with the following line of code:

```{r, eval = FALSE}
devtools::install_github("data-edu/tidyLPA", ref = "ab36357")
```

**Comment by cjvanlissa** [comment]
Ps : people can also install the old version from CRAN’s archive:

https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages

Dr. Caspar J. van Lissa
Assistant professor of developmental data science
Utrecht University, dept. Methodology & Statistics
Sjoerd Groenmangebouw C1.19, 3584CH Utrecht, the Netherlands. Secretariat: +31 30 253 4438

**Comment by jrosen48** [comment]
Ahh good to know!
