### ISSUE TITLE
How to each the posterior probabilities without purchase of Mplus?

### ISSUE THREAD

**Issue by zxy1219** [data-edu/tidyLPA#104]
I want to use tidyLPA to run LPA (first step), then estimate the odds ratio between a risk factor and being a specific profile (second step). The second step need to fit a regression model with the posterior probabilities of identified profile as an outcome. So I'm wondering if we can get the posterior probabilities for each profile without a purchase of Mplus? Thanks!

**Comment by cjvanlissa** [comment]
Yes, these are included in the output. You can extract them to a tibble by running get_data() on your tidyLPA object
