### ISSUE TITLE
Add full list of available stats in documentation of compare_solutions

### ISSUE THREAD

**Issue by cjvanlissa** [data-edu/tidyLPA#116]

**Comment by jrosen48** [comment]
would this go in the `@return` field of the documentation for `compare_solutions()`?

Also, it looks like AIC, AWE, BIC, CLC, and KIC are those fit indices - does that sound correct? 

``` r
library(tidyLPA)
#> tidyLPA has received a major update, with a much easier workflow and improved functionality. However, you might have to update old syntax to account for the new workflow. See vignette('introduction-to-major-changes') for details!
#> 
#> Mplus is not installed. Use only package = 'mclust' when calling estimate_profiles().

iris_subset <- sample(nrow(iris), 20) # so examples execute quickly

results <- iris %>%
    subset(select = c("Sepal.Length", "Sepal.Width",
                      "Petal.Length", "Petal.Width")) %>%
    estimate_profiles(1:3) %>%
    compare_solutions()
#> Warning: The solution with the maximum number of classes under
#> consideration was considered to be the best solution according to one or
#> more fit indices. Examine your results with care and consider estimating
#> more classes.

results
#> Compare tidyLPA solutions:
#> 
#>  Model Classes BIC     
#>  1     1       1522.120
#>  1     2       1042.968
#>  1     3       813.050 
#> 
#> Best model according to BIC is Model 1 with 3 classes.
#> 
#> An analytic hierarchy process, based on the fit indices AIC, AWE, BIC, CLC, and KIC (Akogul & Erisoglu, 2017), suggests the best solution is Model 1 with 3 classes.
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jrosen48** [comment]
@cjvanlissa can you let me know about this? We may have a clean list of issues for the first time in... a long, long time! Would like to incorporate this in forthcoming `1.0.3` release.

**Comment by cjvanlissa** [comment]
This is what we have:

`c("LogLik", "AIC", "AWE", "BIC", "CAIC", "CLC", "KIC", "SABIC", "ICL", "Entropy", "prob_min", "prob_max", "n_min", "n_max", "BLRT_val", "BLRT_p")`

**Comment by jrosen48** [comment]
Can you clarify for me why this belongs with `compare_solutions()` (not `estimate_profiles()`)? Since not all of these are used to compare the solutions using the analytic hierarchy process (but are output by `estimate_profiles()`, I wonder if they would belong better with that function's documentation?

Also, do you think we should define/explain each of these in the documentation?

**Comment by cjvanlissa** [comment]
All these fitindices are included with every LPA that is estimated. So they should probably be documented somewhere centrally, and then referred to in the other functions. The AHP function uses the fit indices from the AHP paper by default, but could use any of these.

**Comment by jrosen48** [comment]
got it, thanks.

**Comment by jrosen48** [comment]
@cjvanlissa could you add to those I don't know (or don't know how to accurately or concisely define)? 

- LogLik: Log-likelihood
- AIC: Aikake information criteria
- AWE:
- BIC: Bayesian information criteria
- CAIC: consistent aikake information criteria
- CLC: 
- KIC: 
- SABIC: Sample size-adjusted bayesian information criteria
- ICL:
- Entropy: 
- Prob. Min.:
- Prob. Max.:
- N Min.:
- N Max.:
- BLRT: bootstrapped likelihood test
- BLRT p-value: p-value for the bootstrapped likelihood ratio test

**Comment by cjvanlissa** [comment]
•	LogLik: Log-likelihood of the data, given the model.
•	AIC: Aikake information criterion; based on -2 log-likelihood, and penalized by number of parameters.
•	AWE: Approximate weight of evidence; combines information on model fit and on classification errors (Celeux et al., 1997)
•	BIC: Bayesian information criterion; based on -2 log-likelihood, and penalized by number of parameters adjusted by sample size.
•	CAIC: Consistent Aikake information criterion; based on -2 log-likelihood, and penalized by number of parameters adjusted by sample size.
•	CLC: Classification Likelihood Criterion; based on -2 log-likelihood, and penalized by the entropy (Biernacki, 1997).
•	KIC: Kullback information criterion; based on -2 log-likelihood, and penalized by 3 times the number of parameters -1 (Cavanaugh, 1999).
•	SABIC: Sample size-adjusted bayesian information criterion (Sclove, 1987).
•	ICL: Integrated completed likelihood (Biernacki, Celeux, & Govaert, 2000).
•	Entropy: A measure of classification uncertainty, reverse-coded so that 1 reflects complete certainty of classification, and 0 complete uncertainty (see Celeux & Soromenho, 1996).
•	Prob. Min.: Minimum of the diagonal of the average latent class probabilities for most likely class membership, by assigned class. The minimum should be as high as possible, reflecting greater classification certainty (cases are assigned to classes they have a high probability of belonging to; see Jung & Wickrama, 2008).
•	Prob. Max.: Maximum of the diagonal of the average latent class probabilities for most likely class membership, by assigned class. The maximum should also be as high as possible, reflecting greater classification certainty (cases are assigned to classes they have a high probability of belonging to).
•	N Min.: Proportion of the sample assigned to the smallest class (based on most likely class membership).
•	N Max.: Proportion of the sample assigned to the largest class (based on most likely class membership).
•	BLRT: bootstrapped likelihood test
•	BLRT p-value: p-value for the bootstrapped likelihood ratio test

**Comment by jrosen48** [comment]
Thanks for doing this. Is this added anywhere?

**Comment by cjvanlissa** [comment]
Hey man, I assigned it to you, so you can add this anywhere you want!

**Comment by jrosen48** [comment]
Thanks - so, I should reopen this, right?

**Comment by jrosen48** [comment]
Added to the vignette and referenced in `get_data()`.
