### ISSUE TITLE
get_data should return data in wide format

### ISSUE THREAD

**Issue by cjvanlissa** [data-edu/tidyLPA#117]
Or create function that merges LPA results with original data file

**Comment by jrosen48** [comment]
I agree this is a good idea

**Comment by jrosen48** [comment]
related to #118 

Is there a straightforward way to do something like this using base (especially for `spread()`:

``` r
library(tidyLPA)
#> tidyLPA has received a major update, with a much easier workflow and improved functionality. However, you might have to update old syntax to account for the new workflow. See vignette('introduction-to-major-changes') for details!
#> 
#> Mplus is not installed. Use only package = 'mclust' when calling estimate_profiles().

m <- pisaUSA15[1:100, ] %>%
    select(broad_interest, enjoyment, self_efficacy) %>%
    single_imputation() %>%
    estimate_profiles(3)
#> Error in select(., broad_interest, enjoyment, self_efficacy): could not find function "select"

get_data(m) %>% 
    mutate(Class_prob = paste0("Class_", Class_prob)) %>% 
    spread(Class_prob, Probability)
#> Error in get_data(m): object 'm' not found
```

<sup>Created on 2019-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by cjvanlissa** [comment]
See my pull request: `get_data` returns data in wide format when applied to an object of class `tidyProfile` (one element of a tidyLPA object), or when applied to a `tidyLPA` object of length one. It returns long format when applied to a `tidyLPA` object containing multiple `tidyProfile` analyses (because then the wide format does not make sense).

**Comment by jrosen48** [comment]
Thanks sir!

________________________________

**Comment by jrosen48** [comment]
This was addressed in #122

**Comment by benjaminwnelson** [comment]
Can tidyLPA be used with repeated measures and if so, then should data be in long or wide format? Thanks!

**Comment by cjvanlissa** [comment]
@benjaminwnelson yes it can, but you can't fit a longitudinal model to the data. The data should be in wide format, multilevel mixture models are not available.

**Comment by benjaminwnelson** [comment]
Thank you! Would you advise that after pulling out LPA groups, you could then join that factor variable with a long dataset in order to do MLM modeling with the LPA group membership?

**Comment by cjvanlissa** [comment]
These are substantive questions; I would recommend finding a statistical collaborator who can help out with this. But briefly: The function ?get_data does what you're asking, but this approach ignores classification uncertainty. If entropy is > .90, the resulting bias may be negligible. In other cases, you will need to conduct 3-step analysis, which uses the classification probability matrix (see the literature).

**Comment by benjaminwnelson** [comment]
Yes, will definitely consult on this. Thank you!

**Comment by benjaminwnelson** [comment]
Is there a way to preserve subject_id when using the get_data function? Thank you!
