### ISSUE TITLE
add helper function to extract Mplus model code

### ISSUE THREAD

**Issue by jrosen48** [data-edu/tidyLPA#119]
From a question to the mailing list:

> I think running the same models in Mplus would help my understanding. Do you maybe have codes to run all these mclust models in Mplus? I am new to Mplus and I am not sure how to use it to run the same models that mclust offers.

My response was:

You can simply change the package argument (for estimate_profiles), as follows, to run them in MPlus:

```
 m <- pisaUSA15[1:100, ] %>%
    single_imputation() %>%
    estimate_profiles(2, package = "MplusAutomation") %>% 
    compare_solutions(statistics = c("AIC", "BIC"))
```

It may need some processing, but, the Mplus model code would then be saved to the `m` object; you can access it via:

`m$model_1_class_2$model$input`

I'm wondering whether we should add a helper function to make it easier to extract (and/or save) the code. Are there principled reasons to avoid this?

**Comment by cjvanlissa** [comment]
I don't think we need functions to extract every element of the output... that function exists, and it's called `$` ;)

**Comment by jrosen48** [comment]
Yep, good call.
