### ISSUE TITLE
MclustBootstrap error with large datasets

### ISSUE THREAD

**Issue by nzpsych** [data-edu/tidyLPA#126]
Firstly, thank you for creating tidyLPA - it is incredibly user-friendly. 

I'm trying to use tidyLPA (v1.0.2) to compare a range of solutions for a relatively large dataset (N = 9000) with five variables of interest. However, I am coming up against some errors.

I was able to replicate this using the PISA example in the “Introduction to tidyLPA” vignette.

This code analyzing the first 100 cases of the PISA dataset works fine:

```
pisaUSA15[1:100, ] %>%
    single_imputation() %>%
    estimate_profiles(1:3, 
                      variances = c("equal", "varying"),
                      covariances = c("zero", "varying")) %>% 
    compare_solutions(statistics = c("AIC", "BIC"))
```

However, when amended to cover the whole PISA dataset it returns an error

```
pisaUSA15%>%
    single_imputation() %>%
    estimate_profiles(1:3, 
                      variances = c("equal", "varying"),
                      covariances = c("zero", "varying")) %>% 
    compare_solutions(statistics = c("AIC", "BIC"))

```
output:

```
Error in MclustBootstrap(out$model, nboot = 100, type = "bs", verbose = FALSE) : 
  object must be of class 'Mclust' or 'densityMclust'
```

Looking at each model specification individually I can see that attempting to estimate three profiles using model 6 causes the problem. i.e.

`estimate_profiles(pisaUSA15, 3, models = 6)
`

Do you have any idea of what is happening here and how to prevent this?  I'm at a beginner level with both R and LPA, so apologies if I have overlooked something obvious.

**Comment by jrosen48** [comment]
Thanks for the reprex. I think this is likely due to an error in the underyling mclust software. I'll investigate further~

**Comment by cjvanlissa** [comment]
It's certainly an error in Mclust. @nzpsych , are you using the latest development version from this github repository? It wraps most mclust errors in a more informative (and less disruptive) manner.

**Comment by cjvanlissa** [comment]
I've reported this bug to the Mclust maintainers. Moreover, with the current version of tidyLPA, I cannot reproduce the error of the original poster.
