### ISSUE TITLE
Can you extract out some of these logical chunks to functions?

### ISSUE THREAD

**Issue by a-rosenberg** [data-edu/tidyLPA#127]
https://github.com/data-edu/tidyLPA/blob/427da979353b52e96b89d94f6c81cf1521fff6dc/R/as.tidyLPA.r#L28

Functions with descriptive names

e.g. "check_if_mixture_model()"

**Comment by jrosen48** [comment]
Thanks much @a-rosenberg. Would you be willing to make a pull as an example ???

**Comment by a-rosenberg** [comment]
Yup, I’ll give it a go. @jrosen48

**Comment by jrosen48** [comment]
Closing for now
