### ISSUE TITLE
Question: Merge results with original dataset

### ISSUE THREAD

**Issue by good-marketing** [data-edu/tidyLPA#129]
Hi, 

Thanks for making this package, it is great. I have a question: 

What is the best way to merge the outcome data with the original dataset? 

I know get_data() provides the original data and probs etc. My challenge is that I have a id column (character), which I cannot pass along in the analysis.

Should I assume the data order is the same and bind  (bind_cols) my original dataset to the output of get_data()? This will probably work, but I cannot be 100% certain, which is the problem. 

Thanks,

Bob

**Comment by cjvanlissa** [comment]
Dear Bob,
the order is not changed, so you can just cbind!

**Comment by good-marketing** [comment]
Ok, thanks for your reply.
