### ISSUE TITLE
Return original data unique identifier with get_data()

### ISSUE THREAD

**Issue by bexx-07** [data-edu/tidyLPA#130]
As it works in R for me right now, get_data() only returns the variables that I included in the latent profile construction and the classes, posterior probabilities, etc. It would be useful if there were a way to designate the observations' unique identifier variable in the get_estimates() function so that the output dataset can be merged with the full dataset.

**Comment by cjvanlissa** [comment]
Dear Bexx,

as the order of rows is never altered, you can `cbind()` the get_data to the original data!
