### ISSUE TITLE
few typos

### ISSUE THREAD

**Issue by tangxin09** [data-edu/tidyLPA#131]
Hi,

I spot some typos.
In "The models are specified by passing arguments to the variance and covariance arguments. The possible values for these arguments are:
variances: “equal” and “**zero**”
covariances: “varying”, “equal”, and “zero” ", that zero should be "varying".

In "6. Varying variances and varying covariances (**model 4**)", it should be "model 6".

Xin

**Comment by cjvanlissa** [comment]
Thank you, I fixed these in my latest commit!
