### ISSUE TITLE
How to add priorControl() for BLRT calculation?

### ISSUE THREAD

**Issue by jesselpz** [data-edu/tidyLPA#160]
Hi I worked on a considerable complicated dataset with model 6 (variances = varying, covariances = varying) : 

```
m6p4 <- estimate_profiles(df = x, n_profiles = 4, 
                          variances = "varying", covariances = "varying", 
                          package = "mclust", 
                          prior = priorControl())
```

and found the warning below:

```
Warning message:
In mclustBootstrapLRT(full_data, modelName = mod_name, nboot = ifelse(methods::hasArg("nboot"),  :
  some model(s) could not be fitted!
```

Seems like the data is too complicated to do the BLRT. Tried to leave the warning but the whole calculation took too much time and without any result outtput. I did meet a `similiar `problem before that without prior control, and there were no BICs conducted when profiles number > 4. I added prior = priorControl and it did help to get all BICs I wanted.  Just wonder if adding prior control to mclustBootstrapLRT() could help? I don't know how to do so.

Is there any idea to solve the problem? 

Any advice and guidance would be greatly appreciated. Thank you so much!

**Comment by jesselpz** [comment]
BTW I tried the model 6 in Mclust. And mclustBootstrapLRT returned all the results with prior = priorControl() without warnings. I'd like to do that in tidyLPA :). Cheers.

**Comment by cjvanlissa** [comment]
Yes, I agree that `priorControl()` should be passed to `mclustBootstrapLRT()` as well! Thanks for the tip!

**Comment by cjvanlissa** [comment]
Could you please run `devtools::install_github("cjvanlissa/tidyLPA") ` and see if you can pass arguments as expected?

**Comment by jesselpz** [comment]
@cjvanlissa Yes! It worked very well. I conducted the results with heigh profiles number without warnings. Many thanks! 
Cheers :).

**Comment by jrosen48** [comment]
I think this can be closed
