### ISSUE TITLE
Return warnings?

### ISSUE THREAD

**Issue by franciscowilhelm** [data-edu/tidyLPA#162]
When fitting a model (sorry, non-reproducible example)

```
ana_mclust <- df %>% %>% 
    select("var1", "var2") %>%
    single_imputation() %>%
    estimate_profiles(1:7, models = 1)
```

I get the follow message:
"One or more analyses resulted in warnings! Examine these analyses carefully: model_1_class_5, model_1_class_6, model_1_class_7" 
However, I could not find in the documentation or the available functions how to retrieve the exact warning messages returned from "mclust". How can I retrieve them?

Thanks,
Francisco

**Comment by cjvanlissa** [comment]
The original mclust objects are in the results object, I think this would work:

`ana_mclust[[5]]$model`

Sounds, however, like models with >4 classes are too complex to estimate on these data.

**Comment by franciscowilhelm** [comment]
Thanks a lot, that works!
For example, `ana_mclust[[5]]$model$warnings` returns the warning.

**Comment by aspencage** [comment]
This does not seem to return the warning in `tidyLPA` version `1.1.0`
