### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by ellaaguinaldo** [data-edu/tidyLPA#191]
How does tidy LPA handle missing data?

**Comment by cjvanlissa** [comment]
Read the manual please!

**Comment by ellaaguinaldo** [comment]
I did at chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/viewer.html?pdfurl=https%3A%2F%2Fcran.r-project.org%2Fweb%2Fpackages%2FtidyLPA%2FtidyLPA.pdf&clen=147611&chunk=true.  

But I don't see anything in the manual? Even when I scanned it for "missing" there was nothing. Is there another document you are referring to?

**Comment by cjvanlissa** [comment]
See `?single_imputation`!
