### ISSUE TITLE
Changinh x-axis value labels in plot_profiles

### ISSUE THREAD

**Issue by teindor** [data-edu/tidyLPA#192]
Hello,
I'm using the following code:
plot_profiles(results$model_1_class_6, add_line = T, rawdata = T, sd = F) +ggplot2::xlab("Measures")+
  ggplot2::ylab("Addiction score"). It works okay.
![fa4102d0-cd60-45c8-9da3-c0afb27a642f](https://user-images.githubusercontent.com/79282034/159479812-3f1c69de-a0d1-425b-a2ef-9c76f80f7252.png)

But, I would like to control the names of the values on the x-axis (not the axis labels, the marks labels, i.e., the variables used). I tried to do this:
plot_profiles(results$model_1_class_6, add_line = T, rawdata = T, sd = F)  +ggplot2::xlab("Measures")+
  ggplot2::ylab("Addiction score")+ggplot2::scale_x_discrete(labels = c("add_prob_ch"="Problemetic use baseline", "add_emo_ch"="Emotional gain baseline", "add_envi_ch"="Socio-environmental baseline", "add_prob_ch_t2"="Problemetic use 6mo", "add_emo_ch_t2"="Emotional gain 6mo", "add_envi_ch_2"="Socio-environmental 6mo"))

Now the variable labels goes off. 
![cde19eb9-d073-4457-a155-1f1aa395990c](https://user-images.githubusercontent.com/79282034/159480362-f5c26d4b-b14a-451b-8770-82189315af97.png)
Any suggestions?

**Comment by cjvanlissa** [comment]
I think the X-axis is continuous to allow for jittered points. Try 

```
+ggplot2::scale_x_continuous(breaks = c(1:6), labels = c("add_prob_ch"="Problemetic use baseline", "add_emo_ch"="Emotional gain baseline", "add_envi_ch"="Socio-environmental baseline", "add_prob_ch_t2"="Problemetic use 6mo", "add_emo_ch_t2"="Emotional gain 6mo", "add_envi_ch_2"="Socio-environmental 6mo"))
```

**Comment by teindor** [comment]
It worked. Thank you!
