### ISSUE TITLE
TidyLPA object contains the data two times

### ISSUE THREAD

**Issue by AlexandreGareau** [data-edu/tidyLPA#201]
The data is contained in the `$model$savedata` and is also presnt in `$dff.` The object becomes quite large when running multiple enumeration and constrained model.

Is there a way that I miss in the document to not save the data in the TidyLPA object?

Is this a feature that could be easily added? I'm sorry but I am not an advanced user of R and would not be able implementing such additional feature.

**Comment by cjvanlissa** [comment]
It's not within scope for tidyLPA to allow that much customization; the goal is to provide a uniform interface for LPA across several packages. If you want to keep a low profile, you could look into `MplusAutomation::createMixtures()`, which does not store all the objects in memory, or `tidySEM::mx_profiles()`, which uses OpenMx and returns smaller objects without such redundancy.
