### ISSUE TITLE
update plot_profiles_mplus() to plot estimated standard errors

### ISSUE THREAD

**Issue by jrosen48** [data-edu/tidyLPA#42]
Presently, the standard errors that are plotted are calculated (manually) based on the posterior class / profile - as noted in the vignette, `plot_profiles()` now has the option to plot the bootstrapped standard errors from **mclust**. We should include this functionality for **mplus** output, too.

**Comment by jrosen48** [comment]
Tagging @cjvanlissa in on this just to be aware

**Comment by cjvanlissa** [comment]
If you want, you can use the code from plotMixtures() in https://github.com/cjvanlissa/MplusAutomation/blob/master/R/mixtures.R for this! Should be pretty much plug and play, but let me know if you run into any difficulties adapting it.

**Comment by jrosen48** [comment]
@cjvanlissa is [this (plotMixtures()](https://github.com/cjvanlissa/MplusAutomation/blob/321f4577b978f92641884d2129884fdff89eef84/R/mixtures.R#L200) the right function?

**Comment by cjvanlissa** [comment]
@jrosen48 I think we should hold off on this for a bit until we integrate the new MplusAutomation functions in tidyLPA, because then it will be a minor change.

**Comment by jrosen48** [comment]
Sounds good
