### ISSUE TITLE
Error for plot_profiles_mplus()

### ISSUE THREAD

**Issue by guyuezhenyu** [data-edu/tidyLPA#69]
When I use `estimate_profiles_mplus(d,V1, V2, V3,V4, V5,n_profiles = 2) %>% plot_profiles_mplus()` or `plot_profiles_mplus()`,  I am getting the following error
`Error in mutate_impl(.data, dots) :    Evaluation error: Column C not found in .data.`

**Comment by jrosen48** [comment]
Hi, can you try to run `estimate_profiles_mplus()` on the output of the `estimate_profiles_mplus()` function? I.e.:

```
m <- estimate_profiles_mplus(d, V1, V2, V3, V4, V5, n_profiles = 2)
plot_profiles_mplus(m)
```

**Comment by jrosen48** [comment]
Could you update to the latest development version and let me know if this error still occurs?


```
install.packages("devtools")
devtools::install_github("jrosen48/tidyLPA")
```

**Comment by guyuezhenyu** [comment]
I try to install tidyLPA from GitHub but the error raises again. It doesn't work for me.

```R
> m <- estimate_profiles_mplus(d,V1, V2, V3,V4, n_profiles = 2)
Model Equal variances and covariances fixed to 0 (2 latent profiles)
LogLik is 6100.303
BIC is 12295.074
Entropy is 0.839
> plot_profiles_mplus(m)
Error in mutate_impl(.data, dots) : 
  Evaluation error: Column `C` not found in `.data`.
> m
# A tibble: 1,432 x 8
      V1    V2    V3    V4    ID CPROB1 CPROB2     C
   <dbl> <dbl> <dbl> <dbl> <int>  <dbl>  <dbl> <dbl>
 1  2.5   1.46  1.27  1        1      1      0     1
 2  2.75  1.54  2     1        2      1      0     1
 3  3     1     1.64  1.57     3      1      0     1
 4  2.75  1.18  2.36  1        4      1      0     1
 5  3.25  1     2.18  1        5      1      0     1
 6  2.5   1     2.64  1        6      1      0     1
 7  3.75  1     1.82  1        7      1      0     1
 8  2     1     2.36  1.71     8      1      0     1
 9  3     1.18  2.46  1        9      1      0     1
10  2.5   1.54  2     1       10      1      0     1
# ... with 1,422 more rows
```

**Comment by fuqiangg** [comment]
I have the same problem. As I look through your code of the function, I found that after the chunck of "if plot_post_probs == TRUE....", you have a line of code that " mplus_data <- mplus_data[, -ncol(mplus_data)]", does this line actually removing the last column "C", so the rest of the codes can't run without that column.

**Comment by fuqiangg** [comment]
I figured out that it's because presumably the output would have ID as the last column. But as 'guyuezhenyu' showed in his output, our output of estiamte_profiles_mplus actually produce "ID" in the middle, and "C" in the last column. I'm not sure if this is a difference for Mac users...
