### ISSUE TITLE
[Feature request]: Profile line plots

### ISSUE THREAD

**Issue by peter1328** [data-edu/tidyLPA#82]
It would be great to have the option to make line plots instead of bar plots of the estimated profile parameters. Since it's dependent data within the profiles, it's more intuitive for many researchers applying LPA.

**Comment by jrosen48** [comment]
@peter1328 thanks for your comment. Interesting. @cjvanlissa any thoughts?

**Comment by jrosen48** [comment]
Actually, I think C.J. may be working on plotting functionality that may address the dependency in a different way.
